[tools]
"aqua:anchore/grype" = "0.104.4"
"aqua:anchore/syft" = "1.40.0"
"aqua:ariga/atlas" = "v1.0.0"
"aqua:defenseunicorns/uds-cli" = "0.27.21"
"aqua:google/addlicense" = "1.2.0"
"aqua:google/go-containerregistry" = "0.20.7"
"aqua:goreleaser/goreleaser" = "2.13.3"
"aqua:helm/helm" = "v3.19.4"
"aqua:k3d-io/k3d" = "v5.8.3"
"aqua:kubernetes-sigs/kind" = "v0.31.0"
"aqua:kubernetes/kubernetes/kubectl" = "v1.35.0"
"aqua:marp-team/marp-cli" = "latest"
"aqua:oras-project/oras" = "1.3.0"
"aqua:sigstore/cosign" = "3.0.4"
"aqua:zarf-dev/zarf" = "v0.69.0"
go = "1.25.5"
"go:github.com/go-delve/delve/cmd/dlv" = "v1.25.2"
"go:golang.org/x/tools/cmd/goimports" = "0.41.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.1.4"
"go:honnef.co/go/tools/cmd/staticcheck" = "v0.6.1"
golangci-lint = "2.8.0"
jq = "1.8.1"
node = "25.3.0"
"npm:eslint" = "9.39.2"
"npm:prettier" = "3.7.4"
uv = "0.9.24"
yamllint = "1.38.0"

[env]
CGO_ENABLED  = "0"
MISE_USE_VERSIONS_HOST_TRACK = "0"
