[tools]
"aqua:anchore/grype" = "0.104.2"
"aqua:anchore/syft" = "1.38.2"
"aqua:defenseunicorns/uds-cli" = "0.27.20"
"aqua:google/addlicense" = "1.2.0"
"aqua:google/go-containerregistry" = "0.20.7"
"aqua:goreleaser/goreleaser" = "2.13.1"
"aqua:helm/helm" = "v3.19.4"
"aqua:k3d-io/k3d" = "v5.8.3"
"aqua:kubernetes-sigs/kind" = "v0.31.0"
"aqua:oras-project/oras" = "1.3.0"
"aqua:sigstore/cosign" = "3.0.3"
"aqua:zarf-dev/zarf" = "0.67.0"
go = "1.25.5"
"go:github.com/go-delve/delve/cmd/dlv" = "v1.25.2"
"go:golang.org/x/tools/cmd/goimports" = "0.40.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.1.4"
"go:honnef.co/go/tools/cmd/staticcheck" = "v0.6.1"
golangci-lint = "2.7.2"
jq = "1.8.1"
node = "24.12.0"
"npm:eslint" = "9.39.2"
"npm:prettier" = "3.7.4"
uv = "0.9.18" # required to install yamllint
yamllint = "1.37.1"

[env]
CGO_ENABLED  = "0"
MISE_USE_VERSIONS_HOST_TRACK = "0"
